// AUTO-GENERATED by scripts/enrich-catalog.mjs. Do not edit by hand.
// Re-run `node scripts/enrich-catalog.mjs` to refresh.

export type CatalogEntry = {
  title: string;
  year?: number;
  kind: "movie" | "tv" | null;
  tmdbId: number | null;
  posterUrl: string | null;
  backdropUrl: string | null;
};

export const catalog: CatalogEntry[] = [
  {
    "title": "Lost in Translation",
    "year": 2003,
    "kind": "movie",
    "tmdbId": 153,
    "posterUrl": "https://image.tmdb.org/t/p/w500/3jCLmYDIIiSMPujbwygNpqdpM8N.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/6ITVHoipvxAS8luzKtHTbPaHLtT.jpg"
  },
  {
    "title": "Call Me by Your Name",
    "year": 2017,
    "kind": "movie",
    "tmdbId": 398818,
    "posterUrl": "https://image.tmdb.org/t/p/w500/mZ4gBdfkhP9tvLH1DO4m4HYtiyi.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/fwf4L3r2ZU9ptOB9nOo5nuVLo1i.jpg"
  },
  {
    "title": "The Florida Project",
    "year": 2017,
    "kind": "movie",
    "tmdbId": 394117,
    "posterUrl": "https://image.tmdb.org/t/p/w500/5QnDxdJg1fi6uMSkSi4x8tHsltm.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/lO5c0zG8s1dBPHcRparpNlNGWU9.jpg"
  },
  {
    "title": "Moonlight",
    "year": 2016,
    "kind": "movie",
    "tmdbId": 376867,
    "posterUrl": "https://image.tmdb.org/t/p/w500/qLnfEmPrDjJfPyyddLJPkXmshkp.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/jm1oD3eB08LImSwL1LrzF9AJQ5b.jpg"
  },
  {
    "title": "Past Lives",
    "year": 2023,
    "kind": "movie",
    "tmdbId": 666277,
    "posterUrl": "https://image.tmdb.org/t/p/w500/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/7HR38hMBl23lf38MAN63y4pKsHz.jpg"
  },
  {
    "title": "Aftersun",
    "year": 2022,
    "kind": "movie",
    "tmdbId": 965150,
    "posterUrl": "https://image.tmdb.org/t/p/w500/evKz85EKouVbIr51zy5fOtpNRPg.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/4jdduww9j5RyzO4ITRcuBFhqNN1.jpg"
  },
  {
    "title": "Stranger Things",
    "year": 2016,
    "kind": "tv",
    "tmdbId": 66732,
    "posterUrl": "https://image.tmdb.org/t/p/w500/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/56v2KjBlU4XaOv9rVYEQypROD7P.jpg"
  },
  {
    "title": "The Wonder Years",
    "year": 2021,
    "kind": "tv",
    "tmdbId": 126164,
    "posterUrl": "https://image.tmdb.org/t/p/w500/stTtZ97QiXTvCQFDF6rNfFfFt9K.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/495i0mBxW11e3QVVAVQLt525Sru.jpg"
  },
  {
    "title": "Yellowjackets",
    "year": 2021,
    "kind": "tv",
    "tmdbId": 117488,
    "posterUrl": "https://image.tmdb.org/t/p/w500/xRnGrn7Z7SC0KIBodocoU1QgDZF.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/ibFWJDWS8cTO6s2vZVd2uKDm8p.jpg"
  },
  {
    "title": "Pen15",
    "year": 2019,
    "kind": "tv",
    "tmdbId": 85702,
    "posterUrl": "https://image.tmdb.org/t/p/w500/9rbyzSTXnrPHJZ1YEOQDK8gnNm8.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/ymatnu4tnvlYvtqtHFqh4llpmRN.jpg"
  },
  {
    "title": "Master of None",
    "year": 2015,
    "kind": "tv",
    "tmdbId": 64254,
    "posterUrl": "https://image.tmdb.org/t/p/w500/AcJM86PhgHAfbrF4dMKBaqO3cHV.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/yYnxld9hgTLCOFORequmOK6paj2.jpg"
  },
  {
    "title": "Reservation Dogs",
    "year": 2021,
    "kind": "tv",
    "tmdbId": 95215,
    "posterUrl": "https://image.tmdb.org/t/p/w500/t6hqwD5oQRGgNrZKN71BQYxteC1.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/4vC3CijGu8g2Z1UobwkJpRQHOVO.jpg"
  },
  {
    "title": "The Shape of Water",
    "year": 2017,
    "kind": "movie",
    "tmdbId": 399055,
    "posterUrl": "https://image.tmdb.org/t/p/w500/9zfwPffUXpBrEP26yp0q1ckXDcj.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/abirSHwWgKajV3hXhaIR5lcCIXe.jpg"
  },
  {
    "title": "Annihilation",
    "year": 2018,
    "kind": "movie",
    "tmdbId": 300668,
    "posterUrl": "https://image.tmdb.org/t/p/w500/4YRplSk6BhH6PRuE9gfyw9byUJ6.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/9trZvBr44UGedUOiGo3jgSUw13e.jpg"
  },
  {
    "title": "Pan's Labyrinth",
    "year": 2006,
    "kind": "movie",
    "tmdbId": 1417,
    "posterUrl": "https://image.tmdb.org/t/p/w500/z7xXihu5wHuSMWymq5VAulPVuvg.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/6G6nqSW9S7EHA9HrYl0Z8uo2H7f.jpg"
  },
  {
    "title": "Under the Skin",
    "year": 2013,
    "kind": "movie",
    "tmdbId": 97370,
    "posterUrl": "https://image.tmdb.org/t/p/w500/55wmcXJIDYITr7JDijJTdvwSaAv.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/eS5OdKN3kRZXQbWRSSCJ4Gh0z26.jpg"
  },
  {
    "title": "Nope",
    "year": 2022,
    "kind": "movie",
    "tmdbId": 762504,
    "posterUrl": "https://image.tmdb.org/t/p/w500/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/yRutvYkM3OP8N9oqqfjSK1VC7fs.jpg"
  },
  {
    "title": "Color Out of Space",
    "year": 2019,
    "kind": "movie",
    "tmdbId": 548473,
    "posterUrl": "https://image.tmdb.org/t/p/w500/k7rD7LzlsPS4jmE6Siah0QO4tAc.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/vj2gCvD5vZDJ865izTU0J0wJBVc.jpg"
  },
  {
    "title": "There Will Be Blood",
    "year": 2007,
    "kind": "movie",
    "tmdbId": 7345,
    "posterUrl": "https://image.tmdb.org/t/p/w500/fa0RDkAlCec0STeMNAhPaF89q6U.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/9UAKA6ceZi6TgQwTAAMt7DWwYPI.jpg"
  },
  {
    "title": "The Master",
    "year": 2012,
    "kind": "movie",
    "tmdbId": 68722,
    "posterUrl": "https://image.tmdb.org/t/p/w500/rUSjbyvYWN9H4az8xt0tDtU7I6v.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/6vvt0ghvrrzEB8Z1BLvmHOWUdxw.jpg"
  },
  {
    "title": "Phantom Thread",
    "year": 2017,
    "kind": "movie",
    "tmdbId": 400617,
    "posterUrl": "https://image.tmdb.org/t/p/w500/hgoWjp9Sh0MI97eAMZCnIoVfgvq.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/sJZd1H4cl2Nxhj0nutVCK5pMczL.jpg"
  },
  {
    "title": "Drive My Car",
    "year": 2021,
    "kind": "movie",
    "tmdbId": 758866,
    "posterUrl": "https://image.tmdb.org/t/p/w500/a2lxHS6Au35k5XtFQEQW44yWHeH.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/r6aqhlmJmu8Dv5E7QYEruaEXKYm.jpg"
  },
  {
    "title": "The Power of the Dog",
    "year": 2021,
    "kind": "movie",
    "tmdbId": 600583,
    "posterUrl": "https://image.tmdb.org/t/p/w500/kEy48iCzGnp0ao1cZbNeWR6yIhC.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/gAsHuCQMN7mv4uFIvM4ACQ09hPr.jpg"
  },
  {
    "title": "Tár",
    "year": 2022,
    "kind": "movie",
    "tmdbId": 817758,
    "posterUrl": "https://image.tmdb.org/t/p/w500/dRVAlaU0vbG6hMf2K45NSiIyoUe.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/84XcRwKHAw4VXdKOYTSW5ARxFEt.jpg"
  },
  {
    "title": "The Banshees of Inisherin",
    "year": 2022,
    "kind": "movie",
    "tmdbId": 674324,
    "posterUrl": "https://image.tmdb.org/t/p/w500/4yFG6cSPaCaPhyJ1vtGOtMD1lgh.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/1vXD5HXqkhvsXFHE7KmCPZGPR1e.jpg"
  },
  {
    "title": "The Zone of Interest",
    "year": 2023,
    "kind": "movie",
    "tmdbId": 467244,
    "posterUrl": "https://image.tmdb.org/t/p/w500/hUu9zyZmDd8VZegKi1iK1Vk0RYS.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/pnTSOKcYnvdpQNQElAtJM1rWOxH.jpg"
  },
  {
    "title": "Heat",
    "year": 1995,
    "kind": "movie",
    "tmdbId": 949,
    "posterUrl": "https://image.tmdb.org/t/p/w500/e09dLw1Ljtccd2P4NsuUvVtS5du.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/xKsnZDERG1dk95wuZ5q9iks3OL3.jpg"
  },
  {
    "title": "Drive",
    "year": 2011,
    "kind": "movie",
    "tmdbId": 64690,
    "posterUrl": "https://image.tmdb.org/t/p/w500/602vevIURmpDfzbnv5Ubi6wIkQm.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/iymDDg4upZWgpbSeiE1JCjsSPBs.jpg"
  },
  {
    "title": "Uncut Gems",
    "year": 2019,
    "kind": "movie",
    "tmdbId": 473033,
    "posterUrl": "https://image.tmdb.org/t/p/w500/6XN1vxHc7kUSqNWtaQKN45J5x2v.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/eGljNfNCrPhFYG2RXXmmE0OKu5.jpg"
  },
  {
    "title": "Good Time",
    "year": 2017,
    "kind": "movie",
    "tmdbId": 429200,
    "posterUrl": "https://image.tmdb.org/t/p/w500/yE1c9hj5Hf8a9KplAdRdhADqUro.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/5AhkjcqqRxBdpYZ0TeOuTCuOUYq.jpg"
  },
  {
    "title": "Sicario",
    "year": 2015,
    "kind": "movie",
    "tmdbId": 273481,
    "posterUrl": "https://image.tmdb.org/t/p/w500/lz8vNyXeidqqOdJW9ZjnDAMb5Vr.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/fKPgObonYgPgCdu88yjV7Hpn7Dp.jpg"
  },
  {
    "title": "Killing Them Softly",
    "year": 2012,
    "kind": "movie",
    "tmdbId": 64689,
    "posterUrl": "https://image.tmdb.org/t/p/w500/heaz45kpFa4Oa7iLis0OBas68ls.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/4xGuNyCX46pwEpdQISRYiaBXEN7.jpg"
  },
  {
    "title": "Widows",
    "year": 2018,
    "kind": "movie",
    "tmdbId": 401469,
    "posterUrl": "https://image.tmdb.org/t/p/w500/d31SGJSaX29ba5ZUbZcesGoDE7I.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/tkri1hMrb1FhWfb2bWpprsvq9Sd.jpg"
  },
  {
    "title": "Arrival",
    "year": 2016,
    "kind": "movie",
    "tmdbId": 329865,
    "posterUrl": "https://image.tmdb.org/t/p/w500/pEzNVQfdzYDzVK0XqxERIw2x2se.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/uKPbFF08QkRMvIAsgCh1soeyPhZ.jpg"
  },
  {
    "title": "Ex Machina",
    "year": 2014,
    "kind": "movie",
    "tmdbId": 264660,
    "posterUrl": "https://image.tmdb.org/t/p/w500/dmJW8IAKHKxFNiUnoDR7JfsK7Rp.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/uqOuJ50EtTj7kkDIXP8LCg7G45D.jpg"
  },
  {
    "title": "Her",
    "year": 2013,
    "kind": "movie",
    "tmdbId": 152601,
    "posterUrl": "https://image.tmdb.org/t/p/w500/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/nG5zmbVeYlcDhckrPAe06fArywn.jpg"
  },
  {
    "title": "Blade Runner 2049",
    "year": 2017,
    "kind": "movie",
    "tmdbId": 335984,
    "posterUrl": "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/mVr0UiqyltcfqxbAUcLl9zWL8ah.jpg"
  },
  {
    "title": "Dune",
    "year": 2021,
    "kind": "movie",
    "tmdbId": 438631,
    "posterUrl": "https://image.tmdb.org/t/p/w500/gDzOcq0pfeCeqMBwKIJlSmQpjkZ.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/zRKQW58MBEY078AxkHxEJzUskCl.jpg"
  },
  {
    "title": "Dune: Part Two",
    "year": 2024,
    "kind": "movie",
    "tmdbId": 693134,
    "posterUrl": "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg"
  },
  {
    "title": "Interstellar",
    "year": 2014,
    "kind": "movie",
    "tmdbId": 157336,
    "posterUrl": "https://image.tmdb.org/t/p/w500/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/2ssWTSVklAEc98frZUQhgtGHx7s.jpg"
  },
  {
    "title": "Severance",
    "year": 2022,
    "kind": "tv",
    "tmdbId": 95396,
    "posterUrl": "https://image.tmdb.org/t/p/w500/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/ixgFmf1X59PUZam2qbAfskx2gQr.jpg"
  },
  {
    "title": "The Bear",
    "year": 2022,
    "kind": "movie",
    "tmdbId": 2383,
    "posterUrl": "https://image.tmdb.org/t/p/w500/ry4A1Y2udvqyDlVHLtSeP1u9qwJ.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/3wcDKBiMnCEZBIg5ADN1dZ7L44i.jpg"
  },
  {
    "title": "Atlanta",
    "year": 2016,
    "kind": "tv",
    "tmdbId": 67178,
    "posterUrl": "https://image.tmdb.org/t/p/w500/y6wYElX5HaPZItVGJcYGdQO7k8g.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/jBGjbSDRxOEudW9rmQbWDzJUKq9.jpg"
  },
  {
    "title": "Fleabag",
    "year": 2016,
    "kind": "tv",
    "tmdbId": 67070,
    "posterUrl": "https://image.tmdb.org/t/p/w500/27vEYsRKa3eAniwmoccOoluEXQ1.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/hXdQ4MWsEOX6qg6VydKrLb3YJ4g.jpg"
  },
  {
    "title": "Barry",
    "year": 2018,
    "kind": "movie",
    "tmdbId": 3175,
    "posterUrl": "https://image.tmdb.org/t/p/w500/A0byHUHMwZ7dtBQtfZ44QIgDbjo.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/ef6SvWbSfCFlKodJZqpIaTvsRRP.jpg"
  },
  {
    "title": "Succession",
    "year": 2018,
    "kind": "tv",
    "tmdbId": 76331,
    "posterUrl": "https://image.tmdb.org/t/p/w500/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/bcdUYUFk8GdpZJPiSAas9UeocLH.jpg"
  },
  {
    "title": "I Think You Should Leave",
    "year": 2019,
    "kind": "tv",
    "tmdbId": 88728,
    "posterUrl": "https://image.tmdb.org/t/p/w500/26fMaTPRczCrTUOQ5svA1Db7l4h.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/3yA0Zw7jeftK4F51PbnZyJOoNs2.jpg"
  },
  {
    "title": "Spider-Man: Across the Spider-Verse",
    "year": 2023,
    "kind": "movie",
    "tmdbId": 569094,
    "posterUrl": "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/9xfDWXAUbFXQK585JvByT5pEAhe.jpg"
  },
  {
    "title": "The Mitchells vs. the Machines",
    "year": 2021,
    "kind": "movie",
    "tmdbId": 501929,
    "posterUrl": "https://image.tmdb.org/t/p/w500/mI2Di7HmskQQ34kz0iau6J1vr70.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/vsZLf5uog08pAnfsMuDWrsLWUUF.jpg"
  },
  {
    "title": "Spirited Away",
    "year": 2001,
    "kind": "movie",
    "tmdbId": 129,
    "posterUrl": "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg"
  },
  {
    "title": "Princess Mononoke",
    "year": 1997,
    "kind": "movie",
    "tmdbId": 128,
    "posterUrl": "https://image.tmdb.org/t/p/w500/cMYCDADoLKLbB83g4WnJegaZimC.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/gl0jzn4BupSbL2qMVeqrjKkF9Js.jpg"
  },
  {
    "title": "Pinocchio",
    "year": 2022,
    "kind": "movie",
    "tmdbId": 532639,
    "posterUrl": "https://image.tmdb.org/t/p/w500/zaZhjKrJeWczQ3AotKoQObppEbH.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/nnUQqlVZeEGuCRx8SaoCU4XVHJN.jpg"
  },
  {
    "title": "The Act of Killing",
    "year": 2012,
    "kind": "movie",
    "tmdbId": 123678,
    "posterUrl": "https://image.tmdb.org/t/p/w500/sp5B7Tz5ttsgOLnIlCP5uEhtesI.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/1jLaJPdu7dMl0Nk3vLuafDx9PWS.jpg"
  },
  {
    "title": "Stories We Tell",
    "year": 2012,
    "kind": "movie",
    "tmdbId": 128216,
    "posterUrl": "https://image.tmdb.org/t/p/w500/aVDtDW3qP0je1Cy87GDfijG9W4c.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/fm0DYaSpo86VPxw2BU93w237WIl.jpg"
  },
  {
    "title": "Faces Places",
    "year": 2017,
    "kind": "movie",
    "tmdbId": 451995,
    "posterUrl": "https://image.tmdb.org/t/p/w500/1NX6NTj9FiiJwEgRUmEifSzE7Na.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/w4uYP6ebNaLQIjsHcjQhjz3BB2m.jpg"
  },
  {
    "title": "Apollo 11",
    "year": 2019,
    "kind": "movie",
    "tmdbId": 549559,
    "posterUrl": "https://image.tmdb.org/t/p/w500/woLMRroHyoTGoXyxdEeBJEYBFtu.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/el4j0LHk56uH6ErE5FZu2x5UJx8.jpg"
  },
  {
    "title": "Free Solo",
    "year": 2018,
    "kind": "movie",
    "tmdbId": 515042,
    "posterUrl": "https://image.tmdb.org/t/p/w500/v4QfYZMACODlWul9doN9RxE99ag.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/z2uuQasY4gQJ8VDAFki746JWeQJ.jpg"
  },
  {
    "title": "Mad Max: Fury Road",
    "year": 2015,
    "kind": "movie",
    "tmdbId": 76341,
    "posterUrl": "https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/uT895WNwm0aIJRtGizcQhrejWUo.jpg"
  },
  {
    "title": "John Wick",
    "year": 2014,
    "kind": "movie",
    "tmdbId": 245891,
    "posterUrl": "https://image.tmdb.org/t/p/w500/wXqWR7dHncNRbxoEGybEy7QTe9h.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/ff2ti5DkA9UYLzyqhQfI2kZqEuh.jpg"
  },
  {
    "title": "The Raid",
    "year": 2011,
    "kind": "movie",
    "tmdbId": 94329,
    "posterUrl": "https://image.tmdb.org/t/p/w500/Abnm1Ws3JH0ReCfEhLMPwPcMcGO.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/kFD6fVwnrHq085JIHCDXsSIqAZf.jpg"
  },
  {
    "title": "Mission: Impossible – Fallout",
    "year": 2018,
    "kind": "movie",
    "tmdbId": 353081,
    "posterUrl": "https://image.tmdb.org/t/p/w500/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/5jnoAA74Qwb5w6B9FMvnc20n6Ie.jpg"
  },
  {
    "title": "Hereditary",
    "year": 2018,
    "kind": "movie",
    "tmdbId": 493922,
    "posterUrl": "https://image.tmdb.org/t/p/w500/hjlZSXM86wJrfCv5VKfR5DI2VeU.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/gJbTXKNTL6O7r7PzF6ZRkJGBlPp.jpg"
  },
  {
    "title": "Midsommar",
    "year": 2019,
    "kind": "movie",
    "tmdbId": 530385,
    "posterUrl": "https://image.tmdb.org/t/p/w500/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/pYgj8e2Y6RufnSyOA6OnzmxFXxZ.jpg"
  },
  {
    "title": "Get Out",
    "year": 2017,
    "kind": "movie",
    "tmdbId": 419430,
    "posterUrl": "https://image.tmdb.org/t/p/w500/mE24wUCfjK8AoBBjaMjho7Rczr7.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/o8dPH0ZSIyyViP6rjRX1djwCUwI.jpg"
  },
  {
    "title": "The Witch",
    "year": 2015,
    "kind": "movie",
    "tmdbId": 310131,
    "posterUrl": "https://image.tmdb.org/t/p/w500/zap5hpFCWSvdWSuPGAQyjUv2wAC.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/zi2oYYNSSv7t44iSt5YrxHX9PYs.jpg"
  },
  {
    "title": "It Follows",
    "year": 2014,
    "kind": "movie",
    "tmdbId": 270303,
    "posterUrl": "https://image.tmdb.org/t/p/w500/iwnQ1JH1wdWrGYkgWySptJ5284A.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/ikaRI4yMxKOje5SmOlAhOBUnicL.jpg"
  },
  {
    "title": "Everything Everywhere All at Once",
    "year": 2022,
    "kind": "movie",
    "tmdbId": 545611,
    "posterUrl": "https://image.tmdb.org/t/p/w500/u68AjlvlutfEIcpmbYpKcdi09ut.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/ss0Os3uWJfQAENILHZUdX8Tt1OC.jpg"
  },
  {
    "title": "Minari",
    "year": 2020,
    "kind": "movie",
    "tmdbId": 615643,
    "posterUrl": "https://image.tmdb.org/t/p/w500/6mPNdmjdbVKPITv3LLCmQoKs9Zw.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/bKCpRjjTKcr3KAITmwjVMobbBYg.jpg"
  },
  {
    "title": "Lady Bird",
    "year": 2017,
    "kind": "movie",
    "tmdbId": 391713,
    "posterUrl": "https://image.tmdb.org/t/p/w500/gl66K7zRdtNYGrxyS2YDUP5ASZd.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/jwBiY1kE5089i2WpfS1MHDYp3VO.jpg"
  },
  {
    "title": "The Souvenir",
    "year": 2019,
    "kind": "movie",
    "tmdbId": 473019,
    "posterUrl": "https://image.tmdb.org/t/p/w500/2Nj04HsZ0lNkv07JnfBZ0bAIECn.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/kIu6aYaUxBUUfJ0l0sLNW1qh45u.jpg"
  },
  {
    "title": "First Cow",
    "year": 2019,
    "kind": "movie",
    "tmdbId": 558582,
    "posterUrl": "https://image.tmdb.org/t/p/w500/yS41crZ1i0fFxCQbuL7I1Y1VBwm.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/8P3qur5Xh6dsH6xmZ1O2XS7vnc2.jpg"
  },
  {
    "title": "Paterson",
    "year": 2016,
    "kind": "movie",
    "tmdbId": 370755,
    "posterUrl": "https://image.tmdb.org/t/p/w500/AuJ1ZlfqwuAr9H5Qr1U9KILylse.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/5Bk7kYSKAuNrxI5BXpDqlsln2P0.jpg"
  },
  {
    "title": "Columbus",
    "year": 2017,
    "kind": "movie",
    "tmdbId": 414453,
    "posterUrl": "https://image.tmdb.org/t/p/w500/6tk0xmn9k5HjUeXsnhxIa94sFXP.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/xN88RKXxjPAcQsdBz6XavZ00PFh.jpg"
  },
  {
    "title": "Personal Shopper",
    "year": 2016,
    "kind": "movie",
    "tmdbId": 340676,
    "posterUrl": "https://image.tmdb.org/t/p/w500/cdm6qZgmbaIwjKBZnUSGWS4eyM2.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/2I4Pe9EN5NlVC90X1JDrbYObZY5.jpg"
  },
  {
    "title": "Frances Ha",
    "year": 2012,
    "kind": "movie",
    "tmdbId": 121986,
    "posterUrl": "https://image.tmdb.org/t/p/w500/jrq1NoKvsxWCcffVOjegiYwloFN.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/oUVd42KgJWW6YnZLfzI7SDTdcPL.jpg"
  },
  {
    "title": "Wednesday",
    "year": 2022,
    "kind": "tv",
    "tmdbId": 119051,
    "posterUrl": "https://image.tmdb.org/t/p/w500/36xXlhEpQqVVPuiZhfoQuaY4OlA.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg"
  },
  {
    "title": "Bridgerton",
    "year": 2020,
    "kind": "tv",
    "tmdbId": 91239,
    "posterUrl": "https://image.tmdb.org/t/p/w500/uXTg565ahu9RwonCX1V2Hex1NU6.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/6umsRLI7t0ydFwCl0JNEIO0q2LH.jpg"
  },
  {
    "title": "Squid Game",
    "year": 2021,
    "kind": "tv",
    "tmdbId": 93405,
    "posterUrl": "https://image.tmdb.org/t/p/w500/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/2meX1nMdScFOoV4370rqHWKmXhY.jpg"
  },
  {
    "title": "The Crown",
    "year": 2016,
    "kind": "movie",
    "tmdbId": 388191,
    "posterUrl": "https://image.tmdb.org/t/p/w500/8y3G8g7E7SXZ74XDt6gaxyfELse.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/uS9l3dVVJknIgJHFyW7jbTiaequ.jpg"
  },
  {
    "title": "Black Mirror",
    "year": 2011,
    "kind": "tv",
    "tmdbId": 42009,
    "posterUrl": "https://image.tmdb.org/t/p/w500/seN6rRfN0I6n8iDXjlSMk1QjNcq.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/dg3OindVAGZBjlT3xYKqIAdukPL.jpg"
  },
  {
    "title": "Money Heist",
    "year": 2017,
    "kind": "tv",
    "tmdbId": 71446,
    "posterUrl": "https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg"
  },
  {
    "title": "Dark",
    "year": 2017,
    "kind": "movie",
    "tmdbId": 155,
    "posterUrl": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg"
  },
  {
    "title": "Ozark",
    "year": 2017,
    "kind": "tv",
    "tmdbId": 69740,
    "posterUrl": "https://image.tmdb.org/t/p/w500/pCGyPVrI9Fzw6rE1Pvi4BIXF6ET.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/aatG9iVAUL7U7OyFEmupESpOrD2.jpg"
  },
  {
    "title": "Mindhunter",
    "year": 2017,
    "kind": "tv",
    "tmdbId": 67744,
    "posterUrl": "https://image.tmdb.org/t/p/w500/eg2eepJtJeRtCZEUJvIYyb2PnYD.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/lpDVJuIro21gtMj9iXMFKHuroZN.jpg"
  },
  {
    "title": "The Queen's Gambit",
    "year": 2020,
    "kind": "tv",
    "tmdbId": 87739,
    "posterUrl": "https://image.tmdb.org/t/p/w500/zU0htwkhNvBQdVSIKB9s6hgVeFK.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/34OGjFEbHj0E3lE2w0iTUVq0CBz.jpg"
  },
  {
    "title": "Beef",
    "year": 2023,
    "kind": "tv",
    "tmdbId": 207468,
    "posterUrl": "https://image.tmdb.org/t/p/w500/bJxGs0w5RAhaX4fIUQu511rvm0S.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/htGeuCcNhlBe8GTx3izKOsd8frw.jpg"
  },
  {
    "title": "Shōgun",
    "year": 2024,
    "kind": "movie",
    "tmdbId": 34546,
    "posterUrl": "https://image.tmdb.org/t/p/w500/jodipMyJcNwdSDfWJ6Chr2BG84k.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/mc7tt8Xenubu31lW6W1j54rfKgI.jpg"
  },
  {
    "title": "True Detective",
    "year": 2014,
    "kind": "tv",
    "tmdbId": 46648,
    "posterUrl": "https://image.tmdb.org/t/p/w500/zYqVTiHK5ZajYcNzAW7qWte5NWS.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/v8YFr8BbU9qsO8PYIulzTeM6Qk.jpg"
  },
  {
    "title": "Better Call Saul",
    "year": 2015,
    "kind": "tv",
    "tmdbId": 60059,
    "posterUrl": "https://image.tmdb.org/t/p/w500/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/og2jKploGHYnCz68vV1nRSEE0xV.jpg"
  },
  {
    "title": "Breaking Bad",
    "year": 2008,
    "kind": "tv",
    "tmdbId": 1396,
    "posterUrl": "https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg"
  },
  {
    "title": "The Last of Us",
    "year": 2023,
    "kind": "movie",
    "tmdbId": 1100287,
    "posterUrl": "https://image.tmdb.org/t/p/w500/nter1KTaQjmkGCjvSu5u01FoecP.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/lpZRUK5AuFW4Rw6bISIWOBJhS7P.jpg"
  },
  {
    "title": "House of Ninjas",
    "year": 2024,
    "kind": "tv",
    "tmdbId": 210098,
    "posterUrl": "https://image.tmdb.org/t/p/w500/AoEuSoSnwSSnX1YzykDdOiKAZNB.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/yeuK2pEl0rgUZ9Q7yttaRQMjjNc.jpg"
  },
  {
    "title": "Ripley",
    "year": 2024,
    "kind": "movie",
    "tmdbId": 1319558,
    "posterUrl": "https://image.tmdb.org/t/p/w500/psJm3haNg6kBpGxfQ1rxckpfF74.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/mP5UGdueYU21rBetATHOnTOzm0M.jpg"
  },
  {
    "title": "Baby Reindeer",
    "year": 2024,
    "kind": "tv",
    "tmdbId": 241259,
    "posterUrl": "https://image.tmdb.org/t/p/w500/tN9OcbkAOPwHSr1sgMornZtQZBx.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/2qLYxCyxf4fim0X5OqM5FjZqWXu.jpg"
  },
  {
    "title": "The Diplomat",
    "year": 2023,
    "kind": "tv",
    "tmdbId": 203857,
    "posterUrl": "https://image.tmdb.org/t/p/w500/cOKXV0FalCYixNmZYCfHXgyQ0VX.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/v6f9FUDDQfGIv8MLRQwlL0zvRjI.jpg"
  },
  {
    "title": "3 Body Problem",
    "year": 2024,
    "kind": "tv",
    "tmdbId": 108545,
    "posterUrl": "https://image.tmdb.org/t/p/w500/ykZ7hlShkdRQaL2aiieXdEMmrLb.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/ciizJ9Okzt9tBBGK7Q3T14LFT2j.jpg"
  },
  {
    "title": "Avatar: The Last Airbender",
    "year": 2024,
    "kind": "tv",
    "tmdbId": 82452,
    "posterUrl": "https://image.tmdb.org/t/p/w500/lzZpWEaqzP0qVA5nkCc5ASbNcSy.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/imlTCObfzISogbvcwB1dokoXAIc.jpg"
  },
  {
    "title": "One Piece",
    "year": 2023,
    "kind": "movie",
    "tmdbId": 900667,
    "posterUrl": "https://image.tmdb.org/t/p/w500/8ibfhe4P7rhmn3lrPhOZzIJHA2B.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/wghKvEjM7UzQzQcKnGbDjOyQO13.jpg"
  },
  {
    "title": "Heartstopper",
    "year": 2022,
    "kind": "tv",
    "tmdbId": 124834,
    "posterUrl": "https://image.tmdb.org/t/p/w500/wJJt1HG62h3WoGnLcRIbO2nNNkg.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/eGYnmsEs5cutoPQKf2QUlT4RgCH.jpg"
  },
  {
    "title": "Love Is Blind",
    "year": 2020,
    "kind": "tv",
    "tmdbId": 100757,
    "posterUrl": "https://image.tmdb.org/t/p/w500/ovDgO2LPfwdVRfvScAqo9aMiIW.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/vHuoq8HAmBFge8aiiyhHVVtmQr3.jpg"
  },
  {
    "title": "Selling Sunset",
    "year": 2019,
    "kind": "tv",
    "tmdbId": 87826,
    "posterUrl": "https://image.tmdb.org/t/p/w500/wUtoD67q4BnRUwikUbT6M38d5oj.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/zzAPTDTHi7wrP99iD6x940wLjPy.jpg"
  },
  {
    "title": "Cobra Kai",
    "year": 2018,
    "kind": "tv",
    "tmdbId": 77169,
    "posterUrl": "https://image.tmdb.org/t/p/w500/6POBWybSBDBKjSs1VAQcnQC1qyt.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/5NrSIzfcBOFI9HRGV4nRYgMGhDU.jpg"
  },
  {
    "title": "Outer Banks",
    "year": 2020,
    "kind": "tv",
    "tmdbId": 100757,
    "posterUrl": "https://image.tmdb.org/t/p/w500/ovDgO2LPfwdVRfvScAqo9aMiIW.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/vHuoq8HAmBFge8aiiyhHVVtmQr3.jpg"
  },
  {
    "title": "Emily in Paris",
    "year": 2020,
    "kind": "tv",
    "tmdbId": 82596,
    "posterUrl": "https://image.tmdb.org/t/p/w500/c0bkO416OU7YGdOFktk45H8REgL.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/jXTZaHarR9TZiMoQwiQWsGYXqnS.jpg"
  },
  {
    "title": "The Witcher",
    "year": 2019,
    "kind": "tv",
    "tmdbId": 71912,
    "posterUrl": "https://image.tmdb.org/t/p/w500/AoGsDM02UVt0npBA8OvpDcZbaMi.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/foGkPxpw9h8zln81j63mix5B7m8.jpg"
  },
  {
    "title": "Lupin",
    "year": 2021,
    "kind": "movie",
    "tmdbId": 614587,
    "posterUrl": "https://image.tmdb.org/t/p/w500/yEKzkOF0uImcs4CdhPQpF8TwVDE.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/3AQf7ne7L6FsXbphdNDIczC8Bfd.jpg"
  },
  {
    "title": "Berlin",
    "year": 2023,
    "kind": "movie",
    "tmdbId": 384664,
    "posterUrl": "https://image.tmdb.org/t/p/w500/fMXPFsNFWgxi6NCmttI6GJq8pa8.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/kEHu88JMh9Zh4RYcgK7Lo2YZwdW.jpg"
  },
  {
    "title": "Squid Game: The Challenge",
    "year": 2023,
    "kind": "movie",
    "tmdbId": 1214667,
    "posterUrl": "https://image.tmdb.org/t/p/w500/78yTLvtsMntVN1cLfzBuZj870pe.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/i9bhxhUBFZHorvK81GNKMJGj2Kt.jpg"
  },
  {
    "title": "Rebel Ridge",
    "year": 2024,
    "kind": "movie",
    "tmdbId": 646097,
    "posterUrl": "https://image.tmdb.org/t/p/w500/xEt2GSz9z5rSVpIHMiGdtf0czyf.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/cyKH7pDFlxIXluqRyNoHHEpxSDX.jpg"
  },
  {
    "title": "Hit Man",
    "year": 2024,
    "kind": "movie",
    "tmdbId": 974635,
    "posterUrl": "https://image.tmdb.org/t/p/w500/oil3EZwKFp3CWxZnfGfGglesvm9.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/nv6F6tz7r61DUhE7zgHwLJFcTYp.jpg"
  },
  {
    "title": "The Killer",
    "year": 2023,
    "kind": "movie",
    "tmdbId": 800158,
    "posterUrl": "https://image.tmdb.org/t/p/w500/ipkcgvN7h3yZnbYowthloHLKsf4.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/f9Atch0jlzcOT9RbF8UccqfNOpd.jpg"
  },
  {
    "title": "Maestro",
    "year": 2023,
    "kind": "movie",
    "tmdbId": 523607,
    "posterUrl": "https://image.tmdb.org/t/p/w500/kxj7rMco6RNYsVcNwuGAIlfWu64.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/et0G74BxoBgNQEZBkUcVhsgeRFF.jpg"
  },
  {
    "title": "Glass Onion",
    "year": 2022,
    "kind": "movie",
    "tmdbId": 661374,
    "posterUrl": "https://image.tmdb.org/t/p/w500/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/dKqa850uvbNSCaQCV4Im1XlzEtQ.jpg"
  },
  {
    "title": "All Quiet on the Western Front",
    "year": 2022,
    "kind": "movie",
    "tmdbId": 49046,
    "posterUrl": "https://image.tmdb.org/t/p/w500/2IRjbi9cADuDMKmHdLK7LaqQDKA.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/xBwtP27cx8WfjHJVFkpuV6F1RES.jpg"
  },
  {
    "title": "Society of the Snow",
    "year": 2023,
    "kind": "movie",
    "tmdbId": 906126,
    "posterUrl": "https://image.tmdb.org/t/p/w500/2e853FDVSIso600RqAMunPxiZjq.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/md848EEPm3dHZOqwGxxTVwH2vu5.jpg"
  },
  {
    "title": "Carry-On",
    "year": 2024,
    "kind": "movie",
    "tmdbId": 1005331,
    "posterUrl": "https://image.tmdb.org/t/p/w500/sjMN7DRi4sGiledsmllEw5HJjPy.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/rhc8Mtuo3Kh8CndnlmTNMF8o9pU.jpg"
  },
  {
    "title": "Damsel",
    "year": 2024,
    "kind": "movie",
    "tmdbId": 763215,
    "posterUrl": "https://image.tmdb.org/t/p/w500/AgHbB9DCE9aE57zkHjSmseszh6e.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/deLWkOLZmBNkm8p16igfapQyqeq.jpg"
  },
  {
    "title": "Leave the World Behind",
    "year": 2023,
    "kind": "movie",
    "tmdbId": 726209,
    "posterUrl": "https://image.tmdb.org/t/p/w500/29rhl1xopxA7JlGVVsf1UHfYPvN.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/5cRw2QHQz5bp7W2KLdSpZoFoTTw.jpg"
  },
  {
    "title": "Our Planet",
    "year": 2019,
    "kind": "movie",
    "tmdbId": 621561,
    "posterUrl": "https://image.tmdb.org/t/p/w500/rLQWByPlwOyLfQAoDA1t9pQaEKV.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/r6JDDWmVQaLy4OZBnJgH3yi4s8U.jpg"
  },
  {
    "title": "Wild Wild Country",
    "year": 2018,
    "kind": "movie",
    "tmdbId": 482981,
    "posterUrl": "https://image.tmdb.org/t/p/w500/79THplH9WM7y3gRPYM4dcC0IRPw.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/k18DGK5laMQJ8i79YnR509IzuKN.jpg"
  },
  {
    "title": "Making a Murderer",
    "year": 2015,
    "kind": "tv",
    "tmdbId": 64439,
    "posterUrl": "https://image.tmdb.org/t/p/w500/sy2nV3rCcJQaRK5M0NWvvTU7CBx.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/i0bVPXHdvLQzE1Ld8dDwbCj1kOW.jpg"
  },
  {
    "title": "Tiger King",
    "year": 2020,
    "kind": "movie",
    "tmdbId": 1591727,
    "posterUrl": "https://image.tmdb.org/t/p/w500/fQS0eMdYYJIoeEHZ8NezCw7Y6Ic.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/6e6hqL2NYOG9GKafVyLuaNDGYPs.jpg"
  },
  {
    "title": "The Social Dilemma",
    "year": 2020,
    "kind": "movie",
    "tmdbId": 656690,
    "posterUrl": "https://image.tmdb.org/t/p/w500/jcaM6V2tCtu6iMHDsGLBUbaYgYp.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/iYqoT9VBGdGTuLl3cjfbG7ZXDkP.jpg"
  },
  {
    "title": "American Murder: The Family Next Door",
    "year": 2020,
    "kind": "movie",
    "tmdbId": 743601,
    "posterUrl": "https://image.tmdb.org/t/p/w500/jjs3hE3mQlVGTX3u5ZH2EJBJpf3.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/fi5TkN1mqC4HBaKCFX26NRQBYTC.jpg"
  },
  {
    "title": "13th",
    "year": 2016,
    "kind": "movie",
    "tmdbId": 4488,
    "posterUrl": "https://image.tmdb.org/t/p/w500/uGGpnWHOmWTARVN9wbC1nPxNgps.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/16zzKM5vDxnYiqG6Tg6wOkOLSmj.jpg"
  },
  {
    "title": "Don't F**k with Cats",
    "year": 2019,
    "kind": "tv",
    "tmdbId": 96129,
    "posterUrl": "https://image.tmdb.org/t/p/w500/Crc4XkhLddMTNJfj1iLca0w1Bb.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/5B5hpcQ4hc6ywi1MiauLhs4liem.jpg"
  },
  {
    "title": "Roma",
    "year": 2018,
    "kind": "movie",
    "tmdbId": 426426,
    "posterUrl": "https://image.tmdb.org/t/p/w500/dtIIyQyALk57ko5bjac7hi01YQ.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/zl9uqCl5iUSb50sTk2BPzw6bJnU.jpg"
  },
  {
    "title": "The Irishman",
    "year": 2019,
    "kind": "movie",
    "tmdbId": 398978,
    "posterUrl": "https://image.tmdb.org/t/p/w500/mbm8k3GFhXS0ROd9AD1gqYbIFbM.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/1RDto0tLo8Fhq7OcwgDaM7nECb7.jpg"
  },
  {
    "title": "Marriage Story",
    "year": 2019,
    "kind": "movie",
    "tmdbId": 492188,
    "posterUrl": "https://image.tmdb.org/t/p/w500/2JRyCKaRKyJAVpsIHeLvPw5nHmw.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/wDwQXLDUuiEaaiuWIDBpbqnwYGX.jpg"
  },
  {
    "title": "The Trial of the Chicago 7",
    "year": 2020,
    "kind": "movie",
    "tmdbId": 556984,
    "posterUrl": "https://image.tmdb.org/t/p/w500/ahf5cVdooMAlDRiJOZQNuLqa1Is.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/v8Nf6Y1qL1Q3PWTBezXNPPaXqza.jpg"
  },
  {
    "title": "Mank",
    "year": 2020,
    "kind": "movie",
    "tmdbId": 614560,
    "posterUrl": "https://image.tmdb.org/t/p/w500/4yzTcAtvzyZLLto4z04xobUK9el.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/hBOH4PNnhcGPgZbZjBwkx9gnNxI.jpg"
  },
  {
    "title": "CODA",
    "year": 2021,
    "kind": "movie",
    "tmdbId": 776503,
    "posterUrl": "https://image.tmdb.org/t/p/w500/BzVjmm8l23rPsijLiNLUzuQtyd.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/v85FlkbMYKa5du1glm0YfYNsL2n.jpg"
  },
  {
    "title": "Nomadland",
    "year": 2020,
    "kind": "movie",
    "tmdbId": 581734,
    "posterUrl": "https://image.tmdb.org/t/p/w500/dKT8rGDR55cM1vGn7QZLA9Tg9YC.jpg",
    "backdropUrl": "https://image.tmdb.org/t/p/w1280/563sRDK3rZS31TXCdTY4lfcwrNK.jpg"
  }
];

/**
 * Lookup by case-insensitive title (and optional year for disambiguation).
 * Returns null when the title isn't in the pre-enriched set — callers should
 * fall back to the runtime TMDB lookup in src/lib/tmdb.ts.
 */
export function findInCatalog(title: string, year?: number): CatalogEntry | null {
  const t = title.toLowerCase().trim();
  return (
    catalog.find((e) => e.title.toLowerCase() === t && (year ? e.year === year : true)) ??
    catalog.find((e) => e.title.toLowerCase() === t) ??
    null
  );
}
