// AUTO-GENERATED by scripts/enrich-catalog.mjs. Do not edit by hand.
// Re-run `node scripts/enrich-catalog.mjs` to refresh.
// Live Netflix-US rows: recent movies + series (TMDB Discover) and games (RAWG).

import type { Channel } from "./seedData";

export const freshChannels: Channel[] = [
  {
    "id": "recently-added-movies",
    "category": {
      "title": "Recently Added Movies",
      "tags": [
        "new",
        "recent",
        "movies"
      ],
      "tone": [
        "fresh",
        "current",
        "varied"
      ],
      "moodColor": "#E50914",
      "exemplars": [
        {
          "title": "Voicemails for Isabelle",
          "year": 2026,
          "oneLine": "A young woman's hilariously confessional voicemails to her late sister are un…"
        },
        {
          "title": "Swapped",
          "year": 2026,
          "oneLine": "A small woodland creature and a majestic bird, two natural sworn enemies of t…"
        },
        {
          "title": "Dhurandhar: The Revenge",
          "year": 2026,
          "oneLine": "As rival gangs, corrupt officials and a ruthless Major Iqbal close in, Hamza'…"
        },
        {
          "title": "GOAT",
          "year": 2026,
          "oneLine": "A small goat with big dreams gets a once-in-a-lifetime shot to join the pros…"
        },
        {
          "title": "Apex",
          "year": 2026,
          "oneLine": "A grieving woman pushing her limits on a solo adventure in the Australian wil…"
        },
        {
          "title": "Office Romance",
          "year": 2026,
          "oneLine": "Jackie, President and CEO of Air Cruz, runs a tight ship in her business, inc…"
        },
        {
          "title": "Dhurandhar",
          "year": 2025,
          "oneLine": "A mysterious traveler slips into the heart of Karachi's underbelly and rises…"
        },
        {
          "title": "War Machine",
          "year": 2026,
          "oneLine": "On one last grueling mission during Army Ranger training, a combat engineer m…"
        },
        {
          "title": "My Dearest Assassin",
          "year": 2026,
          "oneLine": "Hunted for her rare blood type, a caged woman vows to fight alongside the ass…"
        },
        {
          "title": "Colors of Evil: Black",
          "year": 2026,
          "oneLine": "Investigating the disappearance of children in a remote Polish town, prosecut…"
        },
        {
          "title": "28 Years Later: The Bone Temple",
          "year": 2026,
          "oneLine": "Dr."
        },
        {
          "title": "Remarkably Bright Creatures",
          "year": 2026,
          "oneLine": "Through unlikely bonds formed during night shifts at a local aquarium, Tova,…"
        },
        {
          "title": "Peaky Blinders: The Immortal Man",
          "year": 2026,
          "oneLine": "After his estranged son gets embroiled in a Nazi plot, self-exiled gangster T…"
        },
        {
          "title": "Anaconda",
          "year": 2025,
          "oneLine": "A group of friends facing mid-life crises head to the rainforest with the int…"
        }
      ]
    },
    "tilePalette": [
      "#2A2A2A",
      "#1F1F1F",
      "#3A3A3A",
      "#252525",
      "#333333"
    ]
  },
  {
    "id": "just-added-series",
    "category": {
      "title": "Just Added Series",
      "tags": [
        "new",
        "recent",
        "series"
      ],
      "tone": [
        "fresh",
        "current",
        "bingeable"
      ],
      "moodColor": "#5B7CB8",
      "exemplars": [
        {
          "title": "I Will Find You",
          "year": 2026,
          "oneLine": "Wrongfully imprisoned for murdering his own son, a father sets out on a despe…"
        },
        {
          "title": "Teach You a Lesson",
          "year": 2026,
          "oneLine": "An inspector from the Educational Rights Protection Bureau (ERPB) who is auth…"
        },
        {
          "title": "BAKI-DOU: The Invincible Samurai",
          "year": 2026,
          "oneLine": "Baki and the strongest Underground Arena fighters face a threat of historical…"
        },
        {
          "title": "Berlin and the Lady with an Ermine",
          "year": 2026,
          "oneLine": "Hungry for a new heist, Berlin summons the gang to Seville and turns an ambit…"
        },
        {
          "title": "Pursuit of Jade",
          "year": 2026,
          "oneLine": "This drama follows Fan Changyu, a butcher’s daughter, and Xie Zheng, a fallen…"
        },
        {
          "title": "My Royal Nemesis",
          "year": 2026,
          "oneLine": "A legendary Joseon villainess reincarnated in a modern actress’s body clashes…"
        },
        {
          "title": "The WONDERfools",
          "year": 2026,
          "oneLine": "A goofy group of townies stumbles into superpowers and fights rising evil as…"
        },
        {
          "title": "Finding Her Edge",
          "year": 2026,
          "oneLine": "A former ice dancer returns to the rink with an exciting new partner while ho…"
        },
        {
          "title": "The Boroughs",
          "year": 2026,
          "oneLine": "In a seemingly perfect retirement community, a crew of unlikely heroes must s…"
        },
        {
          "title": "If Wishes Could Kill",
          "year": 2026,
          "oneLine": "A mysterious app promises wishes — then starts a countdown to death."
        },
        {
          "title": "Nemesis",
          "year": 2026,
          "oneLine": "A relentless LAPD cop becomes obsessed with taking down the master thief behi…"
        },
        {
          "title": "Love in the Clouds",
          "year": 2025,
          "oneLine": "At the annual Qingyun Conference in the Hexu Six Realms, Ji Bozai, a warrior…"
        },
        {
          "title": "Lord of the Flies",
          "year": 2026,
          "oneLine": "After a plane crash, a group of schoolboys find themselves stranded on a trop…"
        },
        {
          "title": "Monster: The Ed Gein Story",
          "year": 2025,
          "oneLine": "The shocking true-life tale of Ed Gein, the infamous murderer and grave robbe…"
        }
      ]
    },
    "tilePalette": [
      "#3D5A8C",
      "#5B7CB8",
      "#2E4670",
      "#456E9F",
      "#6889B5"
    ]
  },
  {
    "id": "netflix-games",
    "category": {
      "title": "Netflix Games",
      "tags": [
        "games",
        "mobile",
        "included"
      ],
      "tone": [
        "playful",
        "pick-up",
        "varied"
      ],
      "moodColor": "#A66EFF",
      "exemplars": [
        {
          "title": "Grand Theft Auto: San Andreas",
          "year": 2004,
          "oneLine": "Action — on Netflix Games."
        },
        {
          "title": "Grand Theft Auto: Vice City",
          "year": 2002,
          "oneLine": "Action — on Netflix Games."
        },
        {
          "title": "Grand Theft Auto III",
          "year": 2001,
          "oneLine": "Shooter, Action — on Netflix Games."
        },
        {
          "title": "Hades",
          "year": 2020,
          "oneLine": "Indie, Adventure — on Netflix Games."
        },
        {
          "title": "Dead Cells",
          "year": 2018,
          "oneLine": "Platformer, Indie — on Netflix Games."
        },
        {
          "title": "Katana ZERO",
          "year": 2019,
          "oneLine": "Platformer, Indie — on Netflix Games."
        },
        {
          "title": "Monument Valley",
          "year": 2014,
          "oneLine": "Casual, Adventure — on Netflix Games."
        },
        {
          "title": "Monument Valley 2",
          "year": 2017,
          "oneLine": "Casual, Adventure — on Netflix Games."
        },
        {
          "title": "Oxenfree",
          "year": 2016,
          "oneLine": "Indie, Adventure — on Netflix Games."
        },
        {
          "title": "Spiritfarer",
          "year": 2020,
          "oneLine": "Indie, Adventure — on Netflix Games."
        },
        {
          "title": "Into the Breach",
          "year": 2018,
          "oneLine": "Strategy, Indie — on Netflix Games."
        },
        {
          "title": "Terra Nil",
          "year": 2023,
          "oneLine": "Casual, Strategy — on Netflix Games."
        },
        {
          "title": "Cozy Grove",
          "year": 2021,
          "oneLine": "Casual, Indie — on Netflix Games."
        },
        {
          "title": "Vampire Survivors",
          "year": 2022,
          "oneLine": "Casual, Indie — on Netflix Games."
        },
        {
          "title": "Braid",
          "year": 2008,
          "oneLine": "Action, Puzzle — on Netflix Games."
        },
        {
          "title": "The Case of the Golden Idol",
          "year": 2022,
          "oneLine": "Indie, Adventure — on Netflix Games."
        },
        {
          "title": "Storyteller",
          "year": 2023,
          "oneLine": "Adventure, Simulation — on Netflix Games."
        },
        {
          "title": "Football Manager 2024",
          "year": 2023,
          "oneLine": "Strategy, Simulation — on Netflix Games."
        }
      ]
    },
    "tilePalette": [
      "#3A2A5A",
      "#4A2E6E",
      "#2E1F46",
      "#5B3D8C",
      "#241633"
    ]
  }
];
